/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIDOMEventTarget.idl"

interface nsIDOMDOMRequest;

[scriptable, builtinclass, uuid(8b5b2aad-deb3-4e19-a79a-259fbff45b99)]
interface nsIDOMBluetoothSocket : nsIDOMEventTarget
{
  nsIDOMDOMRequest close();
};
